version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - http.cors.allow-origin=**
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - max-old-space-size=7000
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
        - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
      - xpack.security.enabled=false
      - max-old-space-size=7000
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - LOGGING_VERBOSE=true
    networks:
      - es-net
    depends_on:
      - elasticsearch
    entrypoint: ["./bin/kibana", "--allow-root"]
    ports:
      - 5601:5601
networks:
  es-net:
    driver: nat